### PR TITLE
to merge student branch

### PR DESCRIPTION
**Pull request by mingz17**
Added Register, Print, Delete, Modify function about student

## Description
I added RegisterStudent, ModifyStudent, DeleteStudent, PrintStudent function.
A duplicate code was found in the part to initialize the number of student. So, I revised this.

## Motivation and Context
It is required for adjustment of student list after lecture selection.
For better readability,  I modified initialization of the number of student. 

## How Has This Been Tested?
As the student list is modified in a course, functions of managing the students' grades can be operated easily.

### CODE REVIEW

**Comment by younghovpak** [comment]
네 내용 확인했습니다!! merge 해주시면 감사하겠습니다!!

**Comment by cj1ne** [comment]
4가지 기능 모두 깔끔하게 잘하신 것 같아요~
충돌난 부분만 해결해서 병합완료 해주시면 될 것 같습니다!

화이팅!

**Comment by Haeeeun** [comment]
확인했습니다~ 수고하셨어용!

**Comment by cj1ne** [comment]
gitignore 수정해서 무시할 파일들 추가되면 그때 병합해주시면 좋겠어요!

**Pull request closed without merging**
