### PR TITLE
[Mod] - Modified file read & write function

### PR DESCRIPTION
**Pull request by cj1ne**
Modified file IO function
## Description

Existing ReadFile and WriteFile function was just about student's name, score in STUDENT structure. I modified ReadFile and WriteFile function to read and write not only student's name, id, score but also assignment score, course's notice and assignment. Also, changed student.txt to sample_course.txt because this text file doens't mean student's information.

## Motivation and Context

Because we changed to include STUDENT structure in COURSE structure, I fixed parameters and to read and write not only student's name, id, score but also assignment score, course's notice and assignment.

## How Has This Been Tested?

After modifying File IO function, I tested it using print function in other menu. For example, I read data from text file and print data in other menu and write data to file after modifying data.

## Screenshots (if appropriate):
default

### CODE REVIEW

**Comment by sssukho** [comment]
후덜덜 확인했습니다..!

**Comment by mingz17** [comment]
파일 읽고 쓰는 기능을 어떻게 수정해야할지 고민 중이었는데
해결해주셔서 감사합니다
병합 부탁드립니다!

**Comment by younghovpak** [comment]
@cj1ne 까다로운 부분이었는데 해결해주셔서 감사합니다!
병합해주세요~

**Comment by Haeeeun** [comment]
중요한 부분이였는데 해결해주셔서 감사합니다! 확인했습니다~

**Pull request merged**
